version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: streamlit
    versions:
    - 0.76.0
    - 0.77.0
    - 0.78.0
  - dependency-name: scipy
    versions:
    - 1.6.1
  - dependency-name: urllib3
    versions:
    - 1.26.3
